# SPDX-FileCopyrightText: 2025 CommonGraph contributors: https://github.com/comodelling/commongraph/CONTRIBUTORS.md
#
# SPDX-License-Identifier: AGPL-3.0-or-later
services:
  backend:
    env_file:
      - ./.env
      - ./.env.development  # Development overrides
    ports:
      - "8000:8000"

  frontend:
    env_file:
      - ./.env
      - ./.env.development  # Development overrides
