services:
  fastapi:
    build: ./backend
    container_name: objnet-fastapi
    ports:
      - "8000:8000"
    environment:
      - DB_TYPE=${DB_TYPE}
      - DOCKER_ENV=true
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:latest
    container_name: objnet-frontend
    ports:
      - "5173:5173"
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
    depends_on:
      fastapi:
        condition: service_started
