services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: objnet-backend
    ports:
      - "8000:8000"
    environment:
      - DB_TYPE=${DB_TYPE}
      - DOCKER_ENV=true
    volumes:
      - ./backend:/app/backend/
      - ./backend/.env:/app/backend/.env
      # Ensure VERSION file is not overwritten by volume mappings
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:latest
    container_name: objnet-frontend
    ports:
      - "5173:5173"
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_started
