site_name: ObjectiveNet Documentation
nav:
  - Introduction: index.md
  - Configuration: configuration.md
  - Modelling:
    - Graph of Change: modelling_graph.md
    - Democratic Support: modelling_support.md
  - Views:
    - Browsing: view_browsing.md
    - Elemental: view_elemental.md
    - User's: view_user.md

theme: readthedocs
markdown_extensions:
  - admonition
docs_dir: docs
