site_name: ObjectiveNet Documentation
nav:
  - Introduction: index.md
  - Developers: developers.md
  - Modelling:
    - Causal Graph: graph.md
    - Democratic Support: democracy.md

theme: readthedocs
markdown_extensions:
  - admonition
docs_dir: docs
