"""Add security question and answer to user

Revision ID: 17dad9d69830
Revises:
Create Date: 2025-02-01 20:05:47.642458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "17dad9d69830"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("security_question", sa.String(), nullable=True))
    op.add_column("user", sa.Column("security_answer", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "security_question")
    op.drop_column("user", "security_answer")
    # ### end Alembic commands ###
