"""add is_admin to user

Revision ID: de8b3bb22e53
Revises: d6c2c5539c74
Create Date: 2025-06-25 23:31:04.237514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8b3bb22e53'
down_revision: Union[str, None] = 'd6c2c5539c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True, server_default=sa.text("false")))

    # 2) backfill existing rows
    op.execute(
        # set to the same boolean you chose above
        'UPDATE "user" SET is_admin = false'
    )

    # ### end Alembic commands ###
    op.alter_column("user", "is_admin", nullable=False)
    op.alter_column("user", "is_admin", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
